## Análise pós-clusterização
***

In [27]:
import pandas as pd
import numpy as np

In [28]:
path = '/Users/felipebarreto/Desktop/TCC/Bases geradas/'
df1 = pd.read_csv('/Users/felipebarreto/Desktop/dados_acidentes_tratados_completo.csv', sep = ',')   ## dados originais tratados
df2 = pd.read_csv(path + 'centroides_padronizados.csv', sep = ';')   ## centróides de cada cluster     //
df3 = pd.read_csv(path + 'variaveis_quanti_agg.csv', sep = ';')      ## igual ao df4, sem padronização // 
df4 = pd.read_csv(path + 'variaveis_quanti_pad_agg.csv', sep = ';')  ## igual ao df3, com padronização // 
df5 = pd.read_csv(path + 'medias_var_cluster.csv', sep = ';', decimal= '.')        ## médias de cada cluster         // 
#df6 = pd.read_csv(path + 'clusters_7.csv', sep = ';') # var quantitativas completas, nem todas foram utilizadas para a clusterização

In [29]:
display(
    df2,
    df5
    )

,Variavel,Cluster 1,Cluster 2,Cluster 3,Cluster 4,Cluster 5
0,mortos,5.107000,-0.220466,-0.158355,-0.315274,1.839516
1,feridos_leves,6.542480,-0.278858,-0.024023,-0.258486,1.704431
2,feridos_graves,6.456210,-0.257417,-0.118154,-0.270474,1.740282
3,ilesos,7.032826,-0.260867,-0.012918,-0.258526,1.511850
4,freq,6.898542,-0.279096,0.013160,-0.261965,1.618512
5,share_tracado_via_tipo_1,0.420942,0.502943,0.147402,-1.370855,0.022591
6,share_is_night,-0.248996,0.100118,-0.135599,-0.112753,-0.134975
7,share_is_weekend,-0.230220,0.036043,-0.226312,0.063877,-0.050074
8,share_is_single_lane,-1.831921,0.453459,-2.105081,0.405498,-0.782432

,cluster,mortos,feridos_leves,feridos_graves,ilesos,freq,share_tracado_via_tipo_1,share_is_night,share_is_weekend,share_is_single_lane
0,Cluster 1,330.333333,5434.958333,1752.125000,20100.000000,13029.416667,0.796727,0.361273,0.438936,0.239425
1,Cluster 2,27.036392,154.287184,66.805380,352.113133,271.884494,0.816505,0.428919,0.489606,0.963220
2,Cluster 3,30.572464,351.565217,101.764493,1023.442029,791.340580,0.730754,0.383245,0.439680,0.152913
3,Cluster 4,21.638889,170.057540,63.527778,358.452381,302.333333,0.364574,0.387672,0.494903,0.948030
4,Cluster 5,144.312821,1689.630769,568.287179,5151.794872,3644.692308,0.700651,0.383366,0.473218,0.571805

### Análise

In [31]:
df = df3.drop(['pessoas','ilesos','ignorados','feridos','veiculos'], axis=1)[[
    'municipio','cluster','freq','mortos','feridos_graves','feridos_leves','share_tracado_via_tipo_1',
    'share_tracado_via_tipo_2','share_is_night','share_is_weekend','share_is_single_lane'
]].drop_duplicates(subset = ['municipio'])


## Separação dos clusters (c1,c2,c3,c4,c5,c6,c7)
n = len(df.cluster.drop_duplicates())
for i in range(1,n + 1):
    globals()['c' + str(i)] = df[df.cluster == i].drop(['cluster'], axis=1)

df.head(5)

,municipio,cluster,freq,mortos,feridos_graves,feridos_leves,share_tracado_via_tipo_1,share_tracado_via_tipo_2,share_is_night,share_is_weekend,share_is_single_lane
0,curitiba,1,23714,581,2872,10382,0.834781,0.155604,0.375221,0.438306,0.106477
1,sao jose,1,20102,191,1928,8828,0.784648,0.205552,0.369018,0.414785,0.043379
2,guarulhos,1,18109,430,1040,8282,0.942239,0.052018,0.410293,0.422055,0.055221
3,betim,1,17601,329,1718,6840,0.784103,0.208625,0.361911,0.489234,0.048804
4,duque de caxias,1,17531,407,1273,6388,0.842393,0.153785,0.380811,0.430152,0.195710

In [32]:
## Tamanho dos clusters
for i in range(1,n+1):
    print(f'Shape cluster {i}: {df[df.cluster == i].shape}')

Shape cluster 1: (24, 11)
Shape cluster 2: (1264, 11)
Shape cluster 3: (276, 11)
Shape cluster 4: (504, 11)
Shape cluster 5: (195, 11)

In [33]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cluster                   5 non-null      object
 1   mortos                    5 non-null      float64
 2   feridos_leves             5 non-null      float64
 3   feridos_graves            5 non-null      float64
 4   ilesos                    5 non-null      float64
 5   freq                      5 non-null      float64
 6   share_tracado_via_tipo_1  5 non-null      float64
 7   share_is_night            5 non-null      float64
 8   share_is_weekend          5 non-null      float64
 9   share_is_single_lane      5 non-null      float64
dtypes: float64(9), object(1)
memory usage: 528.0+ bytes

In [34]:
#df5 = df5.set_index('cluster')

df5.style.background_gradient(cmap='Greens')

In [35]:
## Médias dos clusters

(df5
 .style
 .background_gradient(cmap='coolwarm', axis=None, vmin=-1, vmax=1)
 .highlight_null(null_color='#f1f1f1')  # Color NaNs grey
 .set_precision(2))

/var/folders/18/y0jr9hp54pd675hslfp3x72c0000gq/T/ipykernel_13982/1226380748.py:3: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  (df5

In [105]:
df.shape

(2263, 11)

#### Observações:

- Total de Municípios analisados: 2263
- Municípios por região:
    - N ---> 
    - NE --> 
    - CO --> 
    - S ---> 
    - SE -->  
- Municípios por UF:
    -

## Cluster 1

In [100]:
c1.head()

,municipio,freq,mortos,feridos_graves,feridos_leves,share_tracado_via_tipo_1,share_tracado_via_tipo_2,share_is_night,share_is_weekend,share_is_single_lane
312,aguas mornas,1520,77,331,906,0.294737,0.681579,0.325658,0.506579,0.996053
331,bela vista de minas,1408,62,366,930,0.182528,0.799006,0.287642,0.477273,0.990767
346,sao cristovao do sul,1372,71,209,682,0.420554,0.561953,0.389942,0.471574,0.990525
350,campos altos,1357,83,219,796,0.275608,0.708180,0.280766,0.464996,0.973471
354,rancho queimado,1335,66,260,742,0.223221,0.759551,0.284644,0.528090,0.977528

In [101]:
c1.shape

(493, 10)

In [ ]:
c1.groupby('uf')[['freq']].sum().sort_values(by = ['freq'], ascending = False)

     freq
uf
mg  33232
sc  28153
rs  21568
ba  13154
pr  12833
es   6291
al   4140
rj   1772
go   1314
sp   1253
pe    770
ma    712
pi    587
ce    482
se    323
rn    297
pa    239
pb    179
ap    147
ro    103
to     67
ac     33
ms     15
am      3
mt      2

In [ ]:
c1.head(50)

,uf,municipio,freq,mortos,feridos_graves,feridos_leves,share_tracado_via_tipo_1,share_tracado_via_tipo_2,share_is_night,share_is_weekend,share_is_single_lane
312,sc,aguas mornas,1520,77,331,906,0.294737,0.681579,0.325658,0.506579,0.996053
331,mg,bela vista de minas,1408,62,366,930,0.182528,0.799006,0.287642,0.477273,0.990767
346,sc,sao cristovao do sul,1372,71,209,682,0.420554,0.561953,0.389942,0.471574,0.990525
350,mg,campos altos,1357,83,219,796,0.275608,0.708180,0.280766,0.464996,0.973471
354,sc,rancho queimado,1335,66,260,742,0.223221,0.759551,0.284644,0.528090,0.977528
366,es,rio novo do sul,1255,81,243,579,0.431076,0.566534,0.333068,0.451793,0.985657
372,sc,xaxim,1224,63,200,681,0.403595,0.582516,0.406046,0.489379,0.992647
377,sc,alfredo wagner,1201,70,251,816,0.214821,0.771857,0.383014,0.512073,0.993339
379,pr,pato branco,1196,32,190,666,0.529264,0.448161,0.401338,0.433110,0.921405
380,sc,ponte alta,1194,60,193,586,0.440536,0.536013,0.403685,0.474874,0.981575
386,rs,cacapava do sul,1174,51,158,459,0.462521,0.500000,0.410562,0.474446,0.974446
391,rj,parati,1171,57,219,597,0.523484,0.476516,0.403074,0.525192,0.963279
400,rs,cruz alta,1150,52,144,508,0.560870,0.429565,0.402609,0.480870,0.964348
410,sc,santa cecilia,1124,70,220,564,0.547153,0.447509,0.420819,0.484875,0.984875
417,mg,nova uniao,1094,66,283,529,0.420475,0.570384,0.301645,0.514625,0.970750
419,mg,corrego danta,1092,76,235,597,0.248168,0.745421,0.302198,0.454212,0.998168
420,es,iconha,1090,42,181,499,0.580734,0.419266,0.306422,0.447706,0.912844
421,mg,ibia,1082,74,192,644,0.594270,0.386322,0.374307,0.447320,0.990758
434,rs,dois irmaos,1041,25,167,575,0.439962,0.553314,0.379443,0.566763,0.776177
444,sc,joacaba,1015,46,154,561,0.412808,0.556650,0.344828,0.434483,0.975369
445,es,anchieta,1008,93,186,497,0.481151,0.511905,0.353175,0.456349,0.957341
446,sc,anchieta,1008,93,186,497,0.481151,0.511905,0.353175,0.456349,0.957341
451,mg,pouso alto,1004,33,116,580,0.321713,0.658367,0.327689,0.503984,0.999004
464,rs,ijui,975,36,136,521,0.553846,0.437949,0.374359,0.490256,0.991795
478,ba,arataca,934,71,123,408,0.157388,0.838330,0.251606,0.448608,0.998929
482,sc,irani,930,40,178,553,0.392473,0.601075,0.337634,0.487097,0.988172
483,sc,vargem bonita,929,64,188,515,0.325081,0.657696,0.343380,0.473628,0.982777
490,mg,sao domingos do prata,915,81,221,482,0.471038,0.511475,0.382514,0.479781,0.979235
493,rs,bage,904,19,99,337,0.563053,0.430310,0.403761,0.440265,0.997788
506,ba,catu,878,51,178,487,0.578588,0.411162,0.333713,0.495444,0.976082
508,sc,curitibanos,860,62,166,564,0.394186,0.582558,0.391860,0.452326,0.989535
511,mg,pocos de caldas,855,38,177,522,0.497076,0.484211,0.378947,0.500585,0.952047
512,pr,nova laranjeiras,854,86,137,404,0.430913,0.550351,0.343091,0.488290,0.974239
517,rs,marques de souza,844,36,121,430,0.533175,0.445498,0.389810,0.478673,0.951422
523,go,mineiros,832,81,168,466,0.581731,0.407452,0.381010,0.495192,0.965144
526,mg,rio casca,830,34,172,411,0.446988,0.540964,0.367470,0.467470,0.990361
533,rs,pouso novo,816,52,102,370,0.287990,0.699755,0.389706,0.447304,0.904412
534,rs,panambi,815,57,124,476,0.590184,0.396319,0.412270,0.507975,0.974233
535,sc,concordia,814,42,188,442,0.366093,0.630221,0.331695,0.501229,0.993857
538,ba,itapebi,806,90,118,405,0.187345,0.799007,0.254342,0.451613,0.985112
543,rs,lagoa vermelha,799,37,132,447,0.460576,0.529412,0.451815,0.490613,0.987484
551,pr,cornelio procopio,793,32,150,505,0.466583,0.518285,0.403531,0.491803,0.795712
553,mg,alem paraiba,790,66,150,412,0.473418,0.501266,0.451899,0.472152,0.997468
555,ba,sao jose da vitoria,788,65,140,393,0.210660,0.786802,0.267766,0.428934,0.997462
567,es,itapemirim,775,38,114,310,0.433548,0.561290,0.387097,0.424516,0.990968
569,al,satuba,774,43,247,492,0.543928,0.445736,0.351421,0.465116,0.980620
570,mg,inhapim,773,81,241,481,0.486417,0.503234,0.415265,0.540750,0.954722
572,sc,bocaina do sul,767,53,163,472,0.401565,0.590613,0.342894,0.514993,0.994785
573,sc,corupa,764,35,207,531,0.407068,0.565445,0.407068,0.514398,0.976440
574,ba,ibirapitanga,763,119,190,438,0.271298,0.728702,0.296199,0.437746,0.998689